version: '3.8'

services:
  api-gateway:
    build: 
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - LOG_LEVEL=debug
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CONSUL_ADDRESS=consul:8500
      - CONSUL_SERVICE_NAME=api-gateway
      - CONSUL_SERVICE_HOST=api-gateway
    depends_on:
      - consul
    networks:
      - gateway-network

  consul:
    image: hashicorp/consul:1.15
    ports:
      - "8500:8500"  # UI and API
      - "8600:8600/udp"  # DNS
    command: agent -dev -client=0.0.0.0
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge